language: node_js

node_js:
    - "4.2"
    - "node"

cache:
    directories:
        - node_modules

script: "npm run ci"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
